version: '3.1'

services:
  app:
    container_name: almightybook
    image: almightybook:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/almightybook
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass123
    ports:
      - "9080:8080"
  db:
    container_name: almightybookdb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: almightybook
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - "7432:5432"